FROM arm32v7/python:3.7-buster
MAINTAINER Lars von Wedel <vonwedel@me.com>

WORKDIR /usr/src/app

RUN apt-get -y update && apt-get -y upgrade \
        && apt-get install -y bluez

COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./miflora-mqtt-daemon.py", "--config_dir", "/config" ]
